### ISSUE TITLE
폰트가 바로 적용되지 않아 글자가 깜빡이는 이슈

### ISSUE THREAD

**Issue by HanCiHu** [boostcampwm-2021/WEB27-NogariHouse#40]
내용 
- 생각보다 많이 거슬려서 이슈에 등록해놓습니다...
- 폰트를 계속 다시 받아오네요 ㅠㅠ

**Comment by NEM-NE** [comment]
저희랑 비슷한 이슈를 가진 분이 쓴 글이네요 ㅎㅎ
https://ryublock.tistory.com/37

**Comment by iHoHyeon** [comment]
> 저희랑 비슷한 이슈를 가진 분이 쓴 글이네요 ㅎㅎ https://ryublock.tistory.com/37

오 저도 이거 읽어봤는데 저희랑 같은 원인인 것 같아요!

**Comment by NEM-NE** [comment]
빌드하면 해결될 듯?
