### ISSUE TITLE
[BUG]사라진 룸 접속 시 오류

### ISSUE THREAD

**Issue by iHoHyeon** [boostcampwm-2021/WEB27-NogariHouse#70]
## 🐡 **사라진 룸 접속 시 오류**

유저1 에서 방을 생성하고 유저2 에서 방을 확인 한 후 유저1이 방에서 나가서 방이 없어졌을때 유저2가 해당방에 들어가려고 시도하면 존재하지 않는 roomDocumentId 를 검색하고, 결국 null값을 바탕으로 in-room-modal을 만들어주게 되서 오류가 발생하는 이슈가 있습니다.
[PR 참고](https://github.com/boostcampwm-2021/WEB27-NogariHouse/pull/64)

## 📋 **테스크 리스트**

- [x]  `in-room-modal` 내부에서 return 값으로 에러 예외처리 (state, roomInfo 의 값이 유효한지 검사)
- [x]  잘못된 방이라는 알림 뷰 보여주기

**Comment by NEM-NE** [comment]
해결 완료
