### ISSUE TITLE
리팩토링을 해야할 목록을 다 넣어봅시다!

### ISSUE THREAD

**Issue by NEM-NE** [boostcampwm-2021/WEB27-NogariHouse#72]
### 리스트

- [ ]  insertMany에서 insertOne 유틸함수 만들고 변경하기

### eslint 설정관련
- [x]  100글자 제한 : max-len
- [x]  class-methods-use-this (server/src/services/rooms-service)
- [x]  변수에 _ 넣을수 있게 : no-underscore-dangle

### API 관련
- [x]  res.json에 ok 속성 추가하기
- [x] 클라이언트 fetch 요청하는 부분을 index에 모아뒀는데 점점 커지는것 같아요!! 분리하면 좋을것 같습니다

### 스크롤 관련
- [x]  화면이 큰 경우 스크롤이 안내려가요 !!

### 스타일 관련
- [x] 마우스 호버시 클릭 스타일 추가하기
- [x] 이벤트 등록 폼 요소 커스텀 하기

### hook 관련
- [x] useRef 사용시 ~~Ref로 통일하기

### Backend 관련

- [ ] getUserInfo 관련 server, client api 함수 추상화하기

### 채팅 기능 관련

- [x] any 사용한 부분이 많아서... 기능 먼저 구현하고 리팩토링 한번 하도록 하겠습니다 ...
- [x] 채팅 부분은 아직 반응형이 구현이 되어있지 않아요... 잠깐 해보려고 했는데 잘 안되서.. 도와주세요 ㅜㅜ
- [x] url을 이용해서 바로 chatting방 내부로 들어가려고 하면 link로 들어가는게 아니기때문에 상태가 없이 들어가게 되고 그래서 에러가 발생합니다. 에러창을 보여주는것 보다는 try catch로 에러 페이지로 가게 해주거나 아예 다시 채팅방 목록으로 돌아가게 구현해주는게 좋을것 같아요
- [x] 채팅 기록을 지금 한번에 모두 불러오고 있는데 추후에 N개씩 불러오고 위로 스크롤시 더 불러오도록 구현하겠습니다 :)

**Comment by HanCiHu** [comment]
### eslint 설정관련
- 100글자 제한 : max-len
- class-methods-use-this (server/src/services/rooms-service)
- 변수에 _ 넣을수 있게 : no-underscore-dangle

**Comment by HanCiHu** [comment]
socket 관련 부분에서 registerRoomHandler 함수 안에 disconnect 부분이나, 마이크 클릭시 이벤트도 모두 들어가 있는것 같아서...
저는 registerRoomHandler은 말 그대로 Room에 가입할때 사용되는 함수를 묶어두는걸로 생각했어요 !!
마이크 이벤트나 방 내부에서 일어나는 이벤트들은 inRoomEventHandler 같이 따로 만들어서 관리해주는 걸로 해당 부분을 이해했었습니다
