### ISSUE TITLE
[BUG] 마이크 on /off 와 초록색 테두리 충돌문제

### ISSUE THREAD

**Issue by iHoHyeon** [boostcampwm-2021/WEB27-NogariHouse#91]
## 🐡 **[BUG] 마이크 on /off 와 초록색 테두리 충돌문제**

말하는 도중 (초록색 테두리가 나와있는 상태) 에서 마이크를 off하면 초록색 테두리가 계속 보입니다!

![image](https://user-images.githubusercontent.com/74816327/142339836-c9bb2d4f-a922-4c77-881f-a94f7ff25e8e.png)

## 📋 **테스크 리스트**

- [ ]  Todo 1

**Comment by NEM-NE** [comment]
@iHoHyeon  마이크가 off 될 때 스타일 기본으로 바꿔주도록 수정했습니다
